services:
  - type: web
    name: progres-web-portal
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://progres.mesrs.dz/api
      - key: NEXT_PUBLIC_PROXY_URL
        value: https://buvfbqwsfcjiqdrqczma.supabase.co/functions/v1/proxy-progres

